extra-keys = [['ESC','TAB','CTRL','ALT','|','~','/','\\'],['{','}','[',']','(',')','<','>'],['-','_','=','+',':',';','"',"'"]]
extra-keys-style = default
extra-keys-text-all-caps = true
extra-keys-text-color = ffffffff
extra-keys-background-color = ff1e1e1e
#terminal-cursor-style = bar
#terminal-cursor-style = block
terminal-cursor-style = underline
terminal-cursor-blink-rate = 500
enforce-char-based-input = true
use-fullscreen = false