terminal-cursor-style = bar
terminal-cursor-style = block
terminal-cursor-style = underline
terminal-cursor-blink-rate = 500
extra-keys = [['/','ls','$','~','UP','exit','*'],['ex','CTRL','ENTER','LEFT','DOWN','RIGHT','F2']]
